//LOADING 

export const CHANGE_LOADING_DESC = 'CHANGE_LOADING_DESC';
export const CHANGE_LOADING_UPD = 'CHANGE_LOADING_UPD';
export const CHANGE_LOADING_SP = 'CHANGE_LOADING_SP';

//AUTHENTICATION 

export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const CHANGE_PRESENT_STATUS = 'CHANGE_PRESENT_STATUS';